apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ivolve-final-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YoussefAzozz/argocd-ivolve-final.git'
    path: overlays/prod
    targetRevision: master
  destination: 
    server: 'https://kubernetes.default.svc'
    namespace: ivolve
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

